README.md

1. Update README.md for more comprehensive.

chore: update make function specification

---

.pre-commit-config.yaml
examples/env.py
examples/vision_env.py
pyproject.toml
safety_gymnasium/bases/underlying.py
safety_gymnasium/vector/sync_vector_env.py

Describe your changes in detail.

fix(CI): pylint version

---

safety_gymnasium/tasks/safety_velocity/safety_ant_velocity.py
safety_gymnasium/tasks/safety_velocity/safety_half_cheetah_velocity.py
safety_gymnasium/tasks/safety_velocity/safety_hopper_velocity.py
safety_gymnasium/tasks/safety_velocity/safety_humanoid_velocity.py
safety_gymnasium/tasks/safety_velocity/safety_swimmer_velocity.py
safety_gymnasium/tasks/safety_velocity/safety_walker2d_velocity.py
safety_gymnasium/utils/passive_env_checker.py

chore: fix type warning

---

safety_gymnasium/assets/xmls/ant.xml
safety_gymnasium/assets/xmls/car.xml
safety_gymnasium/assets/xmls/point.xml
safety_gymnasium/assets/xmls/racecar.xml

1. Update the style of agents.

chore: update the style of agents

---

MANIFEST.in
safety_gymnasium/version.py
setup.py

1. Add more information to setup.py.
2. Add MANIFEST.in to include asset files when uploading to Pypi.

chore: add more information to setup.py

---

README.md

Describe your changes in detail.

chore(README): update pic link and pip

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/questions.yml
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
README.md
docs/index.rst
docs/introduction/basic_usage.rst
pyproject.toml
setup.py

1. `Safety-Gymnaisum` to `safety-gymnasium`.
2. update contents.
3. update changelog for version `0.1.0b0`.

docs: update Changelog and README

---

safety_gymnasium/builder.py

1. Fix confliction of seed mechanism in vector env module.

fix: fix confliction of seed mechanism in vector env module

---

CHANGELOG.md
README.md
safety_gymnasium/version.py

1. Release the first stable version 0.1.0.

chore: release the first stable version 0.1.0

---

.pre-commit-config.yaml
safety_gymnasium/bases/base_task.py
safety_gymnasium/utils/random_generator.py
safety_gymnasium/world.py

1. Fix one bug in the observation space of compass.

fix: fix bug in the observation space of compass

---

.github/dependabot.yml

Describe your changes in detail.

refactor: refine dependabot.yml

---

examples/vision_env.py
safety_gymnasium/bases/underlying.py

1. Update default resolution of vision environments.

chore(vision_env): update default resolution of vision environments

---

CHANGELOG.md
README.md

Describe your changes in detail.

docs: update example and changelog

---

safety_gymnasium/builder.py

In Windows platform, the seed setting in ``builder.py`` has bug. 
We fix this bug by setting the type of seed
close #31 

fix(builder.py): fix seed setting

---

safety_gymnasium/version.py

chore: release v0.1.3

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/questions.yml
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
README.md
docs/conf.py
docs/index.rst
docs/introduction/basic_usage.rst
pyproject.toml
safety_gymnasium/bases/base_task.py
setup.py

1. Update organization information.

chore: update link to `OmniSafeAi` org

---

README.md
pyproject.toml
safety_gymnasium/bases/underlying.py
safety_gymnasium/tasks/safety_velocity/safety_ant_velocity_v0.py
safety_gymnasium/tasks/safety_velocity/safety_half_cheetah_velocity_v0.py
safety_gymnasium/tasks/safety_velocity/safety_hopper_velocity_v0.py
safety_gymnasium/tasks/safety_velocity/safety_humanoid_velocity_v0.py
safety_gymnasium/tasks/safety_velocity/safety_swimmer_velocity_v0.py
safety_gymnasium/tasks/safety_velocity/safety_swimmer_velocity_v1.py
safety_gymnasium/tasks/safety_velocity/safety_walker2d_velocity_v0.py
safety_gymnasium/utils/keyboard_viewer.py
safety_gymnasium/utils/registration.py
tests/test_env.py
tests/test_vision_env.py

1. Update gymnasium version to 0.28.1

deps(gymnasium): update gymnasium version to 0.28.1

---

README.md
docs/spelling_wordlist.txt
safety_gymnasium/__init__.py
safety_gymnasium/agents/__init__.py
safety_gymnasium/agents/doggo.py
safety_gymnasium/assets/xmls/doggo.xml
safety_gymnasium/version.py
tests/test_env.py

feat(agents): support Doggo agent

---

CITATION.cff
README.md

chore: add CITATION.cff

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/questions.yml
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
README.md
benchmarks/README.md
docs/conf.py
docs/index.rst
docs/introduction/basic_usage.rst
pyproject.toml
safety_gymnasium/bases/base_task.py

1. Update link to `PKU-Alignment` org

chore: update link to `PKU-Alignment` org

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

docs: update changelog

---

README.md
safety_gymnasium/version.py

fix(readme): fix typo in readme

---

.github/workflows/tests.yml
.pre-commit-config.yaml
Makefile
docs/requirements.txt
safety_gymnasium/agents/ant.py
safety_gymnasium/agents/car.py
safety_gymnasium/agents/doggo.py
safety_gymnasium/agents/point.py
safety_gymnasium/agents/racecar.py
safety_gymnasium/bases/base_agent.py
safety_gymnasium/tasks/safe_multi_agent/safe_mujoco_multi.py
safety_gymnasium/vector/async_vector_env.py
safety_gymnasium/wrappers/rescale_action.py

1. Update versions of pre-commit repos.

chore(pre-commit): update versions of pre-commit repos

---

docs/requirements.txt

1. Fix docs dependency version.

chore(docs): fix docs dependency version

---

safety_gymnasium/builder.py

fix(builder): fix bug in builder

---

README.md

chore(README): update README.md

---

.pre-commit-config.yaml
Makefile
pyproject.toml
safety_gymnasium/__init__.py
safety_gymnasium/builder.py
safety_gymnasium/tasks/safe_multi_agent/bases/base_agent.py
safety_gymnasium/tasks/safe_multi_agent/builder.py
safety_gymnasium/tasks/safe_vla/__init__.py
safety_gymnasium/tasks/safe_vla/abstract_task.py
safety_gymnasium/tasks/safe_vla/abstract_task_sampler.py
safety_gymnasium/tasks/safe_vla/fetch_task.py
safety_gymnasium/tasks/safe_vla/multi_task_eval_sampler.py
safety_gymnasium/tasks/safe_vla/object_nav_task.py
safety_gymnasium/tasks/safe_vla/pickup_task.py
safety_gymnasium/tasks/safe_vla/task_specs.py
safety_gymnasium/version.py
safety_gymnasium/wrappers/__init__.py
tests/test_config_env.py

Support safety tasks,such as safety object navigation, safety pickup, safety fetch etc.

feat: support safe `VLA` tasks
